name=input('Kimi no namaye nandesuka')
age=int(input('Enter your age'))
print("My name is", name, "and iam", age,"years old")
print(f'My name is {name} and iam {age} years old')
print("My name is"  +name+ "and iam"  +str(age)+  "years old")
